// Central icon barrel. Re-exports only the lucide-react icons the app uses, so
// icon swaps happen in one place and tree-shaking stays intact. Import from
// here (`../ui/icons`) rather than reaching into `lucide-react` directly.
export {
  // App-shell nav
  LayoutDashboard,
  BrainCircuit,
  Zap,
  Swords,
  Library,
  FolderOpen,
  User,
  // KPIs / metrics
  Target,
  Gauge,
  Timer,
  Flame,
  TrendingUp,
  TrendingDown,
  Crosshair,
  ListChecks,
  // Section headers
  AudioWaveform,
  LayoutGrid,
  BarChart3,
  CalendarDays,
  Trophy,
  Sparkles,
  ShieldAlert,
  Activity,
  ClipboardList,
  BookOpen,
  Award,
  // UI controls
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ChevronsUpDown,
  ChevronsLeft,
  ChevronsRight,
  PanelLeftClose,
  PanelLeftOpen,
  Settings2,
  Search,
  Bell,
  Menu,
  X,
  ArrowRight,
  ArrowUpRight,
  Plus,
  Trash2,
  RefreshCw,
  Clock,
  CircleAlert,
  CheckCircle2,
} from 'lucide-react';
